# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
        docker:
      - image: cimg/base:stable
      
    steps:
        - run: echo "build job"
        - run: 
            name: run rollback job
            command: |
                curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
                --header 'Content-Type: application/json' \
                -u "${CIRCLE_TOKEN}:" \
                -d '{
                              "parameters": {
                                "rollback_job": true
                              }
                            }'
      
            when: on_fail       
