name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
#         with:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        id: Cypress_id
        if: steps.autotagger.outputs.tagname != ''
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: Version ${{ steps.autotagger.outputs.version }}
          build: npm run build
          start: npm run dev
          
      
      - name: Rollback Release
        if: failure() && steps.Cypress_id.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.Cypress_id.id }}
          # Using a tag name
          tag: ${{ steps.autotagger.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
