version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build' 

      - cypress/run:
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm run dev'
                
      # - cypress/rollback:
      #     command: |
      #                   curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
      #                   --header 'Content-Type: application/json' \
      #                   -u "${CIRCLE_TOKEN}:" \
      #                   -d '{
      #                                 "parameters": {
      #                                   "rollback_job": true
      #                                 }
      #                               }'

      #     when: on_fail   
          
      
